java.sql.SQLTransientConnectionException: Database 'derby_dir/name2' shutdown.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at spec.benchmarks.derby.DerbyHarness$Client.handleAccounts(DerbyHarness.java:89)
	at spec.benchmarks.derby.DerbyHarness$Client.run(DerbyHarness.java:46)
	at spec.benchmarks.derby.DerbyHarness.<init>(DerbyHarness.java:282)
	at spec.benchmarks.derby.DerbyHarness.main(DerbyHarness.java:248)
	at spec.benchmarks.derby.Main.runBenchmark(Main.java:29)
	at spec.benchmarks.derby.Main.harnessMain(Main.java:143)
	at spec.harness.BenchmarkThread.runLoop(BenchmarkThread.java:170)
	at spec.harness.BenchmarkThread.executeIteration(BenchmarkThread.java:132)
	at spec.harness.BenchmarkThread.run(BenchmarkThread.java:59)
Caused by: java.sql.SQLException: Database 'derby_dir/name2' shutdown.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
Caused by: ERROR 08006: Database 'derby_dir/name2' shutdown.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.shutdownDatabaseException(Unknown Source)
	... 15 more
java.sql.SQLTransientConnectionException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkIfClosed(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.setupContextStack(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.rollback(Unknown Source)
	at spec.benchmarks.derby.DerbyHarness$Client.handleAccounts(DerbyHarness.java:118)
	at spec.benchmarks.derby.DerbyHarness$Client.run(DerbyHarness.java:46)
	at spec.benchmarks.derby.DerbyHarness.<init>(DerbyHarness.java:282)
	at spec.benchmarks.derby.DerbyHarness.main(DerbyHarness.java:248)
	at spec.benchmarks.derby.Main.runBenchmark(Main.java:29)
	at spec.benchmarks.derby.Main.harnessMain(Main.java:143)
	at spec.harness.BenchmarkThread.runLoop(BenchmarkThread.java:170)
	at spec.harness.BenchmarkThread.executeIteration(BenchmarkThread.java:132)
	at spec.harness.BenchmarkThread.run(BenchmarkThread.java:59)
Caused by: java.sql.SQLException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 16 more
sumB: 0
sumD: 0
sumT: 0
min call time: 10.0
max call time: 9992.72818
mean call time: 4403.352953843430
